angular/angular-fr

public/_includes/_main-nav.jade
public/_includes/_scripts-include.jade
public/localization/translate.js
public/resources/css/_translate.scss
public/resources/css/main.scss
public/resources/js/controllers/app-controller.js

This PR adds the ability of toggling the language on the top of the page like the Chinese page does and now the Spanish one too.
You can also toggle languages by clicking on a paragraph / title.

chore: ability to toggle the english language

---

public/docs/ts/latest/tutorial/_data.json
public/docs/ts/latest/tutorial/index.jade
public/docs/ts/latest/tutorial/toh-pt1.jade
public/docs/ts/latest/tutorial/toh-pt2.jade

issue #36
docs(tutorial): french translation (_datas, index, pt1, pt2) fix after PR

docs(tutorial): french translation (_datas, index, pt1, pt2)

---

public/docs/ts/latest/guide/component-styles.jade

Please check if the PR fulfills these requirements
The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
Tests for the changes have been added (for bug fixes / features)
Docs have been added / updated (for bug fixes / features)
Please provide the issue number?
issue #15
Did you finish translating the whole issue?
yes (pr_state: PLEASE_REVIEW)
What kind of change does this PR introduce? (check one with "x")
Translation
Other... Please describe:

Component styles#15

---

public/docs/ts/latest/guide/animations.jade

docs(guide): french translation (animations)

---

public/docs/ts/latest/glossary.jade

docs(glossary): french translation (a to c)

---

public/docs/ts/latest/guide/typescript-configuration.jade

There was no issue associated with that

docs(guide): french translation (typescript-configuration)

---

public/docs/ts/latest/guide/webpack.jade

docs(guide): french translation (webpack)

---

public/docs/ts/latest/guide/webpack.jade

Fixes a few typos in Webpack guide

docs(translation): fix typos in french Webpack section

---

public/docs/ts/latest/glossary.jade

docs(glossary): french translation (d to e)

---

public/docs/ts/latest/guide/_data.json
public/docs/ts/latest/guide/architecture.jade

docs(guide): french translation (architecture)

---

public/docs/ts/latest/guide/attribute-directives.jade

Docs TS: guide attribute-directives

---

public/docs/ts/latest/tutorial/_data.json
public/docs/ts/latest/tutorial/toh-pt3.jade
public/docs/ts/latest/tutorial/toh-pt4.jade

docs(tutorial): french translation(_datas, pt3, pt4) (#37)

---

public/docs/ts/latest/tutorial/toh-pt4.jade

issue #37
Corrections au niveau de l'orthographe, redirection sur un lien français pour les fonctions fléchées

docs(ts): spell check(toh-pt4.jade)

---

public/docs/ts/latest/tutorial/_data.json
public/docs/ts/latest/tutorial/toh-pt5.jade

docs(tutorial): french translation(_datas, pt5)

---

public/docs/ts/latest/guide/lifecycle-hooks.jade

docs(ts): translation of guide lifecycle-hooks

---

public/docs/ts/latest/guide/_data.json
public/docs/ts/latest/guide/structural-directives.jade

docs(ts): translation of structural-directives

---

public/docs/ts/latest/guide/forms.jade

docs(guides): french translation(forms)

---

public/404.jade
public/_data.json
public/_includes/_cta-bar.jade
public/_includes/_footer.jade
public/_includes/_hero-home.jade
public/_includes/_hero.jade
public/_includes/_hover-card.jade
public/_includes/_main-nav.jade
public/_includes/_next-item.jade
public/_layout.jade
public/about/_data.json
public/about/index.jade
public/cardboard/_data.json
public/cardboard/index.jade
public/contribute.jade
public/events.jade
public/features.jade
public/index.jade
public/news.jade
public/presskit.jade
public/support.jade
public/survey.html

docs (public): translation of public files (#2)

---

public/docs/ts/latest/quickstart.jade

docs (public): translation of quickstart (#6)

---

public/docs/_examples/security/ts/app/bypass-security.component.html
public/docs/_examples/security/ts/app/bypass-security.component.ts
public/docs/_examples/security/ts/app/inner-html-binding.component.html
public/docs/_examples/security/ts/app/inner-html-binding.component.ts
public/docs/ts/latest/guide/security.jade

docs(guide): Security french translation

---

public/docs/ts/latest/tutorial/toh-pt6.jade

docs(tutorial): french translation(pt6)
